"""Offline inspection of sparse measured associations, with no texture filling."""
from __future__ import annotations
import base64
import html
import json
import numpy as np


def _encode(array, dtype):
    return base64.b64encode(np.asarray(array, dtype=dtype).tobytes()).decode('ascii')


def _finite(values):
    return [float(x) if np.isfinite(x) else None for x in values]


def write_viewer(out, records, rows, spectra, summary):
    points = np.concatenate([r['points'] for r in records.values()])
    colours = np.concatenate([r['colours'] for r in records.values()])
    centre = (points.min(0)+points.max(0))/2
    scale = max(float(np.ptp(points, axis=0).max()), 1e-9)
    stride = max(1, int(np.ceil(len(points)/250000)))
    metadata = dict(centre=centre.tolist(), scale=scale, displayed_context_points=len(points[::stride]),
                    original_context_points=len(points), context_stride=stride,
                    xyz=_encode((points[::stride]-centre)/scale,'<f4'),
                    rgb=_encode(np.rint(np.clip(colours[::stride],0,1)*255),'u1'),
                    warning=summary['warning'], coordinate_unit=summary['coordinate_unit'], sensors={}, associations=[])
    for sensor, arrays in spectra.items():
        metadata['sensors'][sensor] = dict(wavelength_nm=arrays['wavelength_nm'].tolist(),
                                          index_names=arrays.get('index_names',np.array([])).tolist())
    for item in rows:
        data=spectra[item['sensor_id']]; i=item['sample_index']
        record=dict(item, xyz_display=((np.array(item['xyz_upright'])-centre)/scale).tolist(),
                    raw_DN=data['raw_DN'][i].tolist(), band_quality_flags=data['band_quality_flags'][i].tolist())
        for key in ('Q_assumed_or_confirmed_dark','Q_zero_offset','indices_dark','indices_zero'):
            if key in data:record[key]=_finite(data[key][i])
        for key in ('index_flags_dark','index_flags_zero'):
            if key in data:record[key]=data[key][i].tolist()
        metadata['associations'].append(record)
    (out/'fusion_data.js').write_text('const FUSION='+json.dumps(metadata,allow_nan=False)+';\n',encoding='utf-8')
    page=PAGE.replace('__TITLE__',html.escape(summary['title'])).replace('__WARNING__',html.escape(summary['warning']))
    downloads=''.join(f'<li><a href="{html.escape(name,quote=True)}">{html.escape(sensor)}: assigned full spectra and XYZ (NPZ)</a></li>' for sensor,name in summary['sensor_products'].items())
    downloads+=''.join(f'<li><a href="{r["packaged_cloud"]}">{html.escape(r["label"])}: unchanged source cloud</a></li>' for r in records.values())
    evidence=''.join(f'<li><a href="{html.escape(e["packaged_path"],quote=True)}">{html.escape(e["id"])}</a></li>' for e in summary['evidence'])
    page=page.replace('__DOWNLOADS__',downloads).replace('__EVIDENCE__',evidence)
    (out/'index.html').write_text(page,encoding='utf-8')


PAGE=r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>__TITLE__</title><style>
*{box-sizing:border-box}body{margin:0;background:#071e29;color:#e6f1f2;font:15px/1.5 system-ui,sans-serif}header{padding:22px 26px;background:#0d2b37;border-bottom:1px solid #345563}h1{font-size:26px;margin:0 0 8px}.eyebrow{color:#8cbbb6;letter-spacing:.12em;font-size:11px;text-transform:uppercase}.warning{color:#ffe0a2;margin:8px 0 0;max-width:115ch;font-size:13px}main{display:grid;grid-template-columns:minmax(0,1fr) 360px}.stage{position:relative;height:72vh;min-height:520px;background:radial-gradient(ellipse at 45% 35%,#174856,#061822)}#view{width:100%;height:100%;display:block;touch-action:none}aside{padding:20px;background:#0b2530;max-height:85vh;overflow:auto}label{display:block;font-size:12px;color:#add0d4;margin:12px 0 4px}select,button{width:100%;padding:9px;border:1px solid #466573;border-radius:5px;background:#122f3a;color:#ecf4f5;font:inherit}button{cursor:pointer}input[type=range]{width:100%;accent-color:#77ddbd}a{color:#8de8d4;overflow-wrap:anywhere}p{font-size:13px}#legend,#detail{white-space:pre-wrap;font-size:12px;color:#c9dde2}#detail{overflow-wrap:anywhere}#curve{width:100%;height:170px;background:#09202b}.badge{position:absolute;top:15px;left:18px;right:18px;pointer-events:none;color:#bce8df;font-size:12px}.hint{position:absolute;bottom:18px;left:18px;right:18px;font-size:12px;color:#bed4db;pointer-events:none}.checks{display:flex;gap:7px;align-items:center}.checks input{width:auto}.extras{padding:26px;display:grid;grid-template-columns:1fr 1fr;gap:25px;border-top:1px solid #355462}h2{font-size:18px}li{margin:8px 0}.error{color:#ffc6b6}.buttons{display:grid;grid-template-columns:1fr 1fr;gap:8px}@media(max-width:850px){main{display:block}.stage{height:60vh;min-height:360px}aside{max-height:none}.extras{grid-template-columns:1fr}header{padding:18px}h1{font-size:23px}}
</style></head><body><header><div class="eyebrow">PhenoFusion3D · measured spectral correspondence review</div><h1>__TITLE__</h1><p class="warning">__WARNING__</p></header>
<main><section class="stage"><canvas id="view" aria-label="Interactive sparse spectral associations on recorded 3D geometry"></canvas><div class="badge" id="badge"></div><div class="hint">Drag to rotate · wheel to zoom · Shift-drag to pan · click an enlarged spectral marker.<br>Marker size is for inspection and does not represent a measured spectral footprint.</div></section><aside>
<label for="sensor">Sensor</label><select id="sensor"></select>
<label for="mode">Displayed measurement</label><select id="mode"><option value="raw_DN">Measured raw DN</option><option value="Q_assumed_or_confirmed_dark">Q · assumed dark correction</option><option value="Q_zero_offset">Q0 · zero offset</option><option value="band_quality_flags">Band quality flags</option><option value="indices_dark">Descriptor from Q</option><option value="indices_zero">Descriptor from Q0</option></select>
<label for="band" id="bandLabel">Recorded wavelength</label><input type="range" id="band" min="0" value="0" step="1"><label for="indexName">Saved provisional descriptor</label><select id="indexName"></select>
<p id="legend" role="status"></p><label for="point">Reviewed association</label><select id="point"></select>
<label class="checks"><input type="checkbox" id="overlay" checked>Show annotation markers through geometry</label>
<label class="checks"><input type="checkbox" id="rgb">Show original RGB context</label>
<div class="buttons"><button id="reset">Front / reset</button><button id="side">Side view</button></div>
<p id="detail"></p><a id="spectrumLink" href="spectra/index.html">Inspect exact source spectrum</a>
<canvas id="curve" aria-label="Selected measured spectrum with explicit missing-band gaps"></canvas><p id="curveCaption"></p>
<p>Grey geometry is spatial context only. Grey markers mean a missing/invalid displayed value. Q and Q0 are uncalibrated reference-relative signals; descriptors are not plant health diagnoses.</p>
</aside></main><div class="extras"><section><h2>Traceable downloads</h2><ul><li><a href="associations.json">Every reviewed correspondence and its source identity</a></li><li><a href="associations.csv">Association table (CSV)</a></li><li><a href="assigned_points_reference.ply">Sparse existing vertices (PLY; spectra in NPZ)</a></li>__DOWNLOADS__<li><a href="summary.json">Scope, hashes and limitations</a></li><li><a href="spectra/index.html">Complete measured spectra inspector and exports</a></li></ul></section><section><h2>Correspondence evidence</h2><ul>__EVIDENCE__</ul><p>Each assignment keeps its exact spectral source row and existing cloud vertex. Nearest-vertex proximity checks local geometry consistency; it does not independently prove cross-camera identity. No spectra are spread to adjacent leaves, hidden surfaces or other plants.</p><p>Display rotation is the documented upright rotation. Original XYZ and upright XYZ are exported separately. Physical units remain conditional.</p></section></div>
<script src="fusion_data.js"></script><script>
const $=id=>document.getElementById(id),D=FUSION,all=D.associations;
function bytes(s){const t=atob(s),b=new Uint8Array(t.length);for(let i=0;i<t.length;i++)b[i]=t.charCodeAt(i);return b}
const canvas=$('view'),gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});
const cx=new Float32Array(bytes(D.xyz).buffer),rgb=bytes(D.rgb),gray=new Uint8Array(rgb.length).fill(94);
let sensor=Object.keys(D.sensors)[0],selected=0,filtered=[],yaw=0,pitch=.40,zoom=1.1,pan=[0,0],drag=null,moved=false;
let markerXYZ=new Float32Array(0),markerColours=new Uint8Array(0),markerBuffers=null;
function option(select,value,text){const o=document.createElement('option');o.value=value;o.textContent=text;select.appendChild(o)}
for(const s of Object.keys(D.sensors))option($('sensor'),s,s);
function shader(type,text){const s=gl.createShader(type);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
let program,loc,pa,ca,cloudBuffers;
function buffer(data){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);return b}
if(gl){program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 p;attribute vec3 c;uniform vec3 right;uniform vec3 up;uniform vec3 toward;uniform vec2 scale;uniform vec2 pan;uniform float size;varying vec3 colour;void main(){gl_Position=vec4(dot(p,right)*scale.x+pan.x,dot(p,up)*scale.y+pan.y,-dot(p,toward)*.7,1.);gl_PointSize=size;colour=c;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 colour;void main(){if(length(gl_PointCoord-.5)>.5)discard;gl_FragColor=vec4(colour,1.);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);loc={};for(const n of ['right','up','toward','scale','pan','size'])loc[n]=gl.getUniformLocation(program,n);pa=gl.getAttribLocation(program,'p');ca=gl.getAttribLocation(program,'c');gl.enableVertexAttribArray(pa);gl.enableVertexAttribArray(ca);gl.clearColor(0,0,0,0);cloudBuffers={p:buffer(cx),c:buffer(gray)};markerBuffers={p:buffer(markerXYZ),c:buffer(markerColours)}}else{$('badge').textContent='WebGL is unavailable. Source spectra, correspondence table and downloads remain usable.'}
function modeValue(row){const mode=$('mode').value,b=Number($('band').value),i=Number($('indexName').value);return mode.startsWith('indices')?(row[mode]||[])[i]:(row[mode]||[])[b]}
function colour(v,lo,hi){if(v===null||v===undefined||!Number.isFinite(v))return [150,150,150];const t=hi>lo?Math.max(0,Math.min(1,(v-lo)/(hi-lo))):.5;return [Math.round(45+210*t),Math.round(195-115*Math.abs(2*t-1)),Math.round(240-210*t)]}
function curve(row){const c=$('curve'),ratio=Math.min(devicePixelRatio||1,2),w=c.clientWidth,h=c.clientHeight;c.width=w*ratio;c.height=h*ratio;const g=c.getContext('2d');g.scale(ratio,ratio);g.fillStyle='#09202b';g.fillRect(0,0,w,h);const mode=$('mode').value,key=mode.startsWith('indices')?(mode==='indices_dark'?'Q_assumed_or_confirmed_dark':'Q_zero_offset'):mode;const values=row[key]||[],wv=D.sensors[sensor].wavelength_nm,finite=values.filter(x=>x!==null&&Number.isFinite(x));g.fillStyle='#c6dade';g.font='11px system-ui';if(!finite.length){g.fillText('No valid values for this measurement.',12,30);$('curveCaption').textContent='Missing values remain missing; no curve was invented.';return}let low=Math.min(...finite),high=Math.max(...finite);if(low===high)high=low+1;g.fillText(high.toPrecision(4),6,13);g.fillText(low.toPrecision(4),6,h-18);g.fillText(wv[0].toFixed(1)+' nm',45,h-3);g.fillText(wv[wv.length-1].toFixed(1)+' nm',w-67,h-3);g.strokeStyle='#72e1c7';g.lineWidth=1.4;g.beginPath();let active=false;for(let i=0;i<values.length;i++){const v=values[i];if(v===null||!Number.isFinite(v)){active=false;continue}const x=45+(w-57)*(wv[i]-wv[0])/(wv[wv.length-1]-wv[0]),y=16+(h-43)*(high-v)/(high-low);if(!active){g.moveTo(x,y);active=true}else g.lineTo(x,y)}g.stroke();$('curveCaption').textContent=key+' · '+finite.length+'/'+values.length+' finite bands; NaN gaps are not connected.'}
function selection(){if(!filtered.length){$('detail').textContent='No reviewed 3D association for this sensor. No assignment inferred.';const c=$('curve');c.getContext('2d').clearRect(0,0,c.width,c.height);$('curveCaption').textContent='No source spectrum selected for this sensor.';$('spectrumLink').href='spectra/index.html?sensor='+encodeURIComponent(sensor);$('spectrumLink').textContent='Inspect measured pixels for this sensor';return}$('spectrumLink').textContent='Inspect exact source spectrum';selected=Math.min(Math.max(0,selected),filtered.length-1);$('point').value=selected;const r=filtered[selected],b=Number($('band').value),v=modeValue(r),nm=D.sensors[sensor].wavelength_nm[b],m=$('mode').value,isIndex=m.startsWith('indices'),j=Number($('indexName').value),flags=isIndex?(r[m==='indices_dark'?'index_flags_dark':'index_flags_zero']||[])[j]:r.band_quality_flags[b],measurement=isIndex?(D.sensors[sensor].index_names[j]+' / '+(m==='indices_dark'?'Q':'Q0')):('band '+b+' ('+nm.toFixed(2)+' nm)');$('detail').textContent=r.feature_description+'\n'+r.id+' · '+r.cloud_id+' vertex '+r.point_index+'\nSource pixel: line '+r.source_scan_line+', column '+r.source_detector_column+'\nSample row '+r.sample_index+' · '+measurement+'\nDisplayed value: '+(v===null||v===undefined?'missing':v)+(isIndex?'\nDescriptor flags: ':'\nBand flags: ')+flags+'\nRGB pair support: '+r.supporting_rgb_pairs+'\nVertex distance: '+r.vertex_distance.toPrecision(4)+' '+D.coordinate_unit+' (not a physical accuracy estimate)\nStatus: provisional; independently unvalidated.';$('spectrumLink').href='spectra/index.html?sensor='+encodeURIComponent(sensor)+'&sample='+r.sample_index+'&band='+b;curve(r)}
function update(){const b=Number($('band').value),mode=$('mode').value,nm=D.sensors[sensor].wavelength_nm[b];$('bandLabel').textContent='Band '+b+' · '+nm.toFixed(2)+' nm';$('band').disabled=mode.startsWith('indices');$('indexName').disabled=!mode.startsWith('indices');const vals=filtered.map(modeValue),finite=vals.filter(v=>v!==null&&Number.isFinite(v)),lo=finite.length?Math.min(...finite):0,hi=finite.length?Math.max(...finite):1;markerColours=Uint8Array.from(vals.flatMap(v=>colour(v,lo,hi)));if(gl){gl.bindBuffer(gl.ARRAY_BUFFER,markerBuffers.c);gl.bufferData(gl.ARRAY_BUFFER,markerColours,gl.DYNAMIC_DRAW)}$('legend').textContent=filtered.length+' sparse associations · '+finite.length+' finite displayed values\n'+(finite.length?'Display colour range '+lo.toPrecision(4)+' to '+hi.toPrecision(4)+'; relative scale for this view.':'No valid values for this selection; markers stay grey.');selection()}
function changeSensor(){sensor=$('sensor').value;filtered=all.filter(r=>r.sensor_id===sensor);selected=0;$('point').innerHTML='';filtered.forEach((r,i)=>option($('point'),i,r.id));const meta=D.sensors[sensor];$('band').max=meta.wavelength_nm.length-1;$('band').value=Math.min(Number($('band').value),meta.wavelength_nm.length-1);$('indexName').innerHTML='';meta.index_names.forEach((n,i)=>option($('indexName'),i,n));if(!meta.index_names.length)option($('indexName'),0,'No saved descriptors');for(const o of $('mode').options)if(o.value.startsWith('indices'))o.disabled=!meta.index_names.length;if(!meta.index_names.length&&$('mode').value.startsWith('indices'))$('mode').value='raw_DN';markerXYZ=Float32Array.from(filtered.flatMap(r=>r.xyz_display));if(gl){gl.bindBuffer(gl.ARRAY_BUFFER,markerBuffers.p);gl.bufferData(gl.ARRAY_BUFFER,markerXYZ,gl.STATIC_DRAW);$('badge').textContent=D.original_context_points.toLocaleString()+' original geometry points · '+D.displayed_context_points.toLocaleString()+' displayed · markers indicate sparse provisional associations'}update()}
$('sensor').onchange=changeSensor;$('mode').onchange=update;$('band').oninput=update;$('indexName').onchange=update;$('point').onchange=e=>{selected=Number(e.target.value);selection()};$('rgb').onchange=()=>{if(gl){gl.bindBuffer(gl.ARRAY_BUFFER,cloudBuffers.c);gl.bufferData(gl.ARRAY_BUFFER,$('rgb').checked?rgb:gray,gl.STATIC_DRAW)}};$('reset').onclick=()=>{yaw=0;pitch=.40;zoom=1.1;pan=[0,0]};$('side').onclick=()=>{yaw=Math.PI/2;pitch=.25;pan=[0,0]};
function axes(){return {r:[Math.cos(yaw),Math.sin(yaw),0],u:[-Math.sin(yaw)*Math.sin(pitch),Math.cos(yaw)*Math.sin(pitch),Math.cos(pitch)],t:[Math.sin(yaw)*Math.cos(pitch),-Math.cos(yaw)*Math.cos(pitch),Math.sin(pitch)]}}
canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);drag=[e.clientX,e.clientY];moved=false};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag[0],dy=e.clientY-drag[1];if(Math.abs(dx)+Math.abs(dy)>2)moved=true;if(e.shiftKey){pan[0]+=dx/canvas.clientWidth*2;pan[1]-=dy/canvas.clientHeight*2}else{yaw-=dx*.007;pitch=Math.max(-Math.PI/2,Math.min(Math.PI/2,pitch+dy*.007))}drag=[e.clientX,e.clientY]};canvas.onpointerup=e=>{drag=null;if(moved)return;const rect=canvas.getBoundingClientRect(),w=rect.width,h=rect.height,ax=axes(),sx=2*zoom/1.22*Math.min(h/w,1),sy=2*zoom/1.22*Math.min(w/h,1),mx=e.clientX-rect.left,my=e.clientY-rect.top;let found=-1,best=225;filtered.forEach((r,i)=>{const p=r.xyz_display,dot=v=>p.reduce((a,x,j)=>a+x*v[j],0),x=(dot(ax.r)*sx+pan[0]+1)*w/2,y=(1-dot(ax.u)*sy-pan[1])*h/2,d=(x-mx)**2+(y-my)**2;if(d<best){best=d;found=i}});if(found>=0){selected=found;selection()}};canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.3,Math.min(10,zoom*Math.exp(-e.deltaY*.001)))},{passive:false});
function bind(buffers){gl.bindBuffer(gl.ARRAY_BUFFER,buffers.p);gl.vertexAttribPointer(pa,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,buffers.c);gl.vertexAttribPointer(ca,3,gl.UNSIGNED_BYTE,true,0,0)}
function draw(){if(!gl)return;const ratio=Math.min(devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*ratio),h=Math.round(canvas.clientHeight*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}const a=axes();gl.uniform3fv(loc.right,a.r);gl.uniform3fv(loc.up,a.u);gl.uniform3fv(loc.toward,a.t);gl.uniform2f(loc.scale,2*zoom/1.22*Math.min(h/w,1),2*zoom/1.22*Math.min(w/h,1));gl.uniform2fv(loc.pan,pan);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);bind(cloudBuffers);gl.uniform1f(loc.size,1.5*ratio);gl.drawArrays(gl.POINTS,0,cx.length/3);if($('overlay').checked)gl.disable(gl.DEPTH_TEST);bind(markerBuffers);gl.uniform1f(loc.size,13*ratio);gl.drawArrays(gl.POINTS,0,filtered.length);if(filtered.length){gl.uniform1f(loc.size,19*ratio);gl.drawArrays(gl.POINTS,selected,1)}requestAnimationFrame(draw)}
changeSensor();if(gl)requestAnimationFrame(draw);window.addEventListener('resize',()=>selection());
</script></body></html>'''
